#!/usr/bin/env bash
#
#  nosord The NOSOR Core server.
#
#
# chkconfig: 345 80 20
# description: nosord
# processname: nosord
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/nosord, see below
if [ -f /etc/sysconfig/nosord ]; then
        . /etc/sysconfig/nosord
fi

RETVAL=0

prog=nosord
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/nosord
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/nosord}

# nosord defaults to /usr/bin/nosord, override with BITCOIND_BIN
nosord=${BITCOIND_BIN-/usr/bin/nosord}

# nosord opts default to -disablewallet, override with BITCOIND_OPTS
nosord_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $nosord $nosord_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
